function(Fileread cfgfile)
    file(READ "${cfgfile}" FileContents )
    string(REPLACE "\n" ";" lines "${FileContents}")
    
    foreach(line ${lines})
        string(REPLACE "=" ";" line_split ${line})
        list(LENGTH line_split count)
        if (count LESS 2)
            message(STATUS "Skipping ${line}")
            continue()
        endif()
        list(GET line_split -1 value)
        string(STRIP "${value}" value)
        list(GET line_split 0 var_name)
        string(STRIP ${var_name} var_name)
        set(${var_name} ${value} PARENT_SCOPE)
    endforeach()
endfunction()

Fileread("PLUGIN_CONFIG")