name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy :
      matrix :
        os : [ windows-latest, macos-latest, ubuntu-latest]
        include :
          - os : windows-latest
            artifact_path : "VST3/Starp.vst3/Contents/x86_64-win/Starp.vst3"
          - os : macos-latest
            artifact_path : "VST3/Starp.vst3/Contents/MacOS/Starp"
          - os : ubuntu-latest
            artifact_path : "VST3/Starp.vst3/Contents/x86_64-win/Starp.so"
    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Configure ubuntu
      if : matrix.os == 'ubuntu-latest'
      run : apt install xorg-dev libasound2-dev libgl1-mesa-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Upload plugin
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.os}}-vst
        path: ${{github.workspace}}/build/Starp_artefacts/Release/${{matrix.artifact_path}}

