name: Windows Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# When pushing new commits, cancel any running builds on that branch
concurrency:
  group: windows-build-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Release
  BUILD_DIR: build
  OS_TAG : win64
  # Just to make vscode happy. These will be set for real
  # in the config-info step
  SF_PROJECT : ""
  SF_VERSION : ""
  SF_PROJ_LOWER : ""
  SF_ARTIFACT_PATH : ""
  SF_BUILD_FILE : ""
  SF_VST3_BUILD_PATH : ""
  SF_VST3_PLUGIN_PATH : ""
  SF_OUTPUT_STEM : ""
  SF_IN_RUNNER : ""

jobs:
    build:
        runs-on: 'windows-latest'
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
              with:
                submodules: true

            - name: Get Config Info
              id: config-info
              shell : bash
              run : |
                ./common/scripts/project_vars.sh > CONFIG.sh
                cat CONFIG.sh
                cat CONFIG.sh >> $GITHUB_ENV
                cat CONFIG.sh >> $GITHUB_OUTPUT

            - name: Build
              uses : SolidFuel/actions/config-build-test@main
              with :
                build_dir: ${{env.BUILD_DIR}}
                type : ${{env.BUILD_TYPE}}
        
            - name: Pluginval
              uses : SolidFuel/actions/test-with-pluginval@main
              with :
                build_dir: ${{env.BUILD_DIR}}
                plugin : ${{env.SF_VST3_PLUGIN_PATH}}
                
            - name: Compress plugin win
              working-directory: ${{github.workspace}}/${{env.BUILD_DIR}}
              run : |
                  Set-Location ${env:SF_VST3_BUILD_PATH}/${env:SF_ARTIFACT_PATH}
                  $ZIPNAME="${env:SF_OUTPUT_STEM}-vst3.zip"
                  Compress-Archive -Path ${env:SF_BUILD_FILE} `
                    -CompressionLevel Optimal `
                    -Destination ${ZIPNAME}     
          
            - name: Upload plugin
              uses: actions/upload-artifact@v3
              with:
                  name: ${{env.SF_OUTPUT_STEM}}-vst3.zip
                  path: ${{github.workspace}}/${{env.BUILD_DIR}}/${{env.SF_OUTPUT_STEM}}-vst3.zip

            - name : setup windows installer file
              working-directory: ${{github.workspace}}
              shell : bash
              run : ./common/scripts/expand_file.sh ./packaging/windows/plugin.iss > ${{env.BUILD_DIR}}/plugin.iss
                
            - name : build windows installer
              working-directory: ${{github.workspace}}
              run: iscc /Dsrcdir="$pwd" ${{env.BUILD_DIR}}\plugin.iss
            
            - name: Upload windows installer
              uses: actions/upload-artifact@v3
              with:
                name: ${{env.SF_OUTPUT_STEM}}-install.exe
                path: ${{github.workspace}}/${{env.BUILD_DIR}}/${{env.SF_PROJ_LOWER}}.exe
            